sudo: required
services:
  - docker

before_install:
  - docker build -t DavidDevOps2000/docker-react -f Dockerfile.dev .

script:
  - docker run DavidDevOps2000/docker-react npm run test -- --coverage